feats/django/urls.py
from django.conf.urls import url

from . import views

app_name = 'feats'
urlpatterns = [
    url(r'^features/([^/]+)/selectors/$', views.AddSelector.as_view(), name='add-selector'),
    url(r'^features/([^/]+)/selectors/([0-9]+)/$', views.ChangeSelector.as_view(), name='update-selector'),
    url(r'^features/([^/]+)/segmentation/$', views.ChangeSegmentation.as_view(), name='update-segmentation'),
    url(r'^features/([^/]+)/segmentation-mapping/$', views.ChangeMapping.as_view(), name='update-mapping'),
    url(r'^features/([^/]+)/$', views.Detail.as_view(), name='detail'),
    url(r'^$', views.Index.as_view(), name='index'),
]

feats/django/views/detail.py
from .base import TemplateView


class Detail(TemplateView):
    template_name = 'feats/detail.html'

    @property
    def feature(self):
        return self.feats_app.features[self.args[0]]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        feature = self.feature
        state = feature.state
        context['feature'] = feature
        context['state'] = state
        if state:
            context['segment_names'] = [
                segment.name for segment in state.segments
            ]
        return context

feats/django/views/selectors.py
from django.http import Http404
from django.http.response import HttpResponseBadRequest, HttpResponseRedirect
from django.utils.functional import cached_property
from django.urls import reverse
from feats import selector
from feats.state import FeatureState
from feats.django.views import base
from feats.django.templatetags.feats import selector_type


class SelectorForm(base.Form):
    name = base.CharField(required=True)

    def __init__(self, _type: str, selector=None, initial=None, *args, **kwargs):
        if selector is not None:
            initial = initial or {}
            initial['name'] = selector.name

        super().__init__(initial=initial, *args, **kwargs)
        self.fields['_type'] = base.HiddenCharField(
            required=True,
            initial=_type
        )


class StaticSelectorForm(SelectorForm):
    def __init__(self, feature_handle, selector=None, initial=None, *args, **kwargs):
        if selector is not None:
            initial = initial or {}
            initial['implementation'] = selector.value

        super().__init__('static', selector, initial, *args, **kwargs)
        self.feature_handle = feature_handle
        self.fields['implementation'] = base.ChoiceField(
            choices=[
                (name, name)
                for name in feature_handle.feature.implementations.keys()
            ],
            required=True,
        )

    def create_selector(self):
        return selector.Static.from_data(
            self.feature_handle.app, {
                'value': self.cleaned_data['implementation'],
                'name': self.cleaned_data['name'],
            }
        )


class WeightedSelectorForm(SelectorForm):
    def __init__(self, feature_handle, _type, selector=None, initial=None, *args, **kwargs):
        if selector is not None:
            initial = initial or {}
            for impl_name, weight in selector.weights.items():
                initial['weights[{}]'.format(impl_name)] = weight

        super().__init__(_type, selector, initial, *args, **kwargs)
        self.feature_handle = feature_handle
        for name in feature_handle.feature.implementations.keys():
            key = 'weights[{}]'.format(name)
            self.fields[key] = base.IntegerField(
                label=name,
                required=True,
                min_value=0,
                initial=0,
            )
            self.fields[key].fieldset = 'Weights'

    def get_weights(self):
        weights = {}
        for name in self.feature_handle.feature.implementations.keys():
            weight = self.cleaned_data['weights[{}]'.format(name)]
            weights[name] = weight
        return weights


class RolloutSelectorForm(WeightedSelectorForm):
    def __init__(self, feature_handle, selector=None, initial=None, *args, **kwargs):
        if selector is not None:
            initial = initial or {}
            initial['segment'] = selector.segment.name

        super().__init__(feature_handle, 'rollout', selector, initial, *args, **kwargs)
        self.fields['segment'] = base.ChoiceField(
            choices=[
                (name, name) for name in feature_handle.valid_segments().keys()
            ],
            required=True,
        )

    def create_selector(self):
        segment = self.cleaned_data['segment']
        name = self.cleaned_data['name']
        weights = self.get_weights()

        return selector.Rollout.from_data(
            self.feature_handle.app, {
                'name': name,
                'weights': weights,
                'segment': segment
            }
        )


class ExperimentSelectorForm(WeightedSelectorForm):
    def __init__(self, feature_handle, selector=None, initial=None, *args, **kwargs):
        super().__init__(feature_handle, 'experiment', selector, initial, *args, **kwargs)

    def create_selector(self):
        name = self.cleaned_data['name']
        weights = self.get_weights()

        return selector.Experiment.from_data(
            self.feature_handle.app, {
                'name': name,
                # Needs App support for registering persisters
                'persister': "# TODO:",
                'weights': weights,
            }
        )


class AddSelector(base.TemplateView):
    template_name = 'feats/add_selector.html'
    forms = {
        'experiment': ExperimentSelectorForm,
        'static': StaticSelectorForm,
        'rollout': RolloutSelectorForm,
    }

    @property
    def feature(self):
        return self.feats_app.features[self.args[0]]

    def create_forms(self):
        """
        Dynamically creates forms for adding each type of selector based on
        the feature it is being created for.
        For rollout & experiment selectors, there is a field per implementation
        for the weight of that implementation.
        For static selectors, the select box's options are populated with each
        implementation.
        """
        feature = self.feature
        data = {}
        if self.request.method == 'POST':
            data[self.request.POST['_type']] = self.request.POST

        init_forms = {}
        for key, form in self.forms.items():
            init_forms[key] = form(
                feature,
                data=data.get(key),
                auto_id='id_{}_%s'.format(key)
            )
        return init_forms

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['feature'] = self.feature
        context['forms'] = self.create_forms()
        return context

    def post(self, request, *args, **kwargs):
        forms = self.create_forms()
        bound_form = None
        for form in forms.values():
            if form.is_bound:
                bound_form = form
                break

        if bound_form is None:
            return HttpResponseBadRequest()

        if bound_form.is_valid():
            feature = self.feature
            selector = form.create_selector()
            state = feature.state
            if state is None:
                state = FeatureState.initial(self.request.user.username)

            state = state.add_selector(
                selector,
                created_by=self.request.user.username
            )
            self.feature.state = state
            return HttpResponseRedirect(
                reverse('feats:detail', args=self.args)
            )

        return HttpResponseBadRequest()


class ChangeSelector(base.TemplateView):
    template_name = 'feats/change_selector.html'
    forms = {
            'feats.selector.Static': StaticSelectorForm,
            'feats.selector.Rollout': RolloutSelectorForm,
            'feats.selector.Experiment': ExperimentSelectorForm,
    }

    @cached_property
    def feature(self):
        return self.feats_app.features[self.args[0]]

    @property
    def selector_idx(self):
        return int(self.args[1])

    @cached_property
    def selector(self):
        return self.state.selectors[self.selector_idx]

    @cached_property
    def state(self):
        state = self.feature.state
        if state is None:
            raise Http404()
        return state

    @cached_property
    def form(self):
        return self.forms[selector_type(self.selector)]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['feature'] = self.feature
        context['form'] = self.form(self.feature, selector=self.selector)
        context['selector'] = self.selector
        return context

    def post(self, request, *args, **kwargs):
        form = self.form(self.feature, data=request.POST, selector=self.selector)
        if form.is_valid():
            if form.has_changed():
                state = self.state.update_selector(
                        self.selector_idx,
                        form.create_selector(),
                        created_by=self.request.user.username,
                )
                self.feature.state = state
            return HttpResponseRedirect(
                reverse('feats:detail', args=self.args[:1])
            )
        return HttpResponseBadRequest()

feats/django/templates/feats/_render_field.html
{% if field.is_hidden %}
{{ field }}
{% else %}
<div class="form-group">
    {{field.label_tag}}
    {{field}}
</div>
{% endif %}

feats/django/templates/feats/_render_form.html
{% for name, fieldset in form.fieldsets %}
<fieldset class="form-group">
    {% if name %}
    <legend>
        {{name}}
    </legend>
    {% endif %}
    {% for field in fieldset %}
    {% include "feats/_render_field.html" with field=field only %}
    {% endfor %}
</fieldset>
{% empty %}
{% for field in form %}
{% include "feats/_render_field.html" with field=field only %}
{% endfor %}
{% endfor %}

feats/django/templates/feats/_selector.html
{% load selector_type from feats %}

{% if selector|selector_type == "feats.selector.Static" %}
{% include "feats/selectors/_static.html" with selector=selector %}
{% elif selector|selector_type == "feats.selector.Rollout" %}
{% include "feats/selectors/_rollout.html" with selector=selector %}
{% elif selector|selector_type == "feats.selector.Experiment" %}
{% include "feats/selectors/_experiment.html" with selector=selector %}
{% else %}
Unknown Selector Type "{{selector|selector_type}}"
{% debug %}
{% endif %}

feats/django/templates/feats/_sidebar.html
{% if features %}
<nav class="list-group list-group-flush h-100">
{% for current_feature in features %}
	    <a
		    {% if current_feature == feature %}
		    class="list-group-item active list-group-action" 
		    {% else %}
		    class="list-group-item list-group-action"
		    {% endif %}
		    href="{% url 'feats:detail' current_feature.name %}">{{current_feature.name}}</a>
{% endfor %}
</nav>
{% else %}
<h1> No Features Registered </h1>
{% endif %}

feats/django/templates/feats/_template.html
<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta name="referrer" content="same-origin">

		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
		<script defer src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
		<script defer src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
		<script defer src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

		<title>Feats{% if feature %} - {{ feature.name }}{% endif %}</title>
		{% block script %}
		{% endblock %}
	</head>
	<body class="container-fluid">
		<header class="row">
			{% block header %}
			<nav class="navbar navbar-dark bg-primary col">
				<a class="navbar-brand" href="{% url "feats:index" %}">Feats</a>
				{% if feature %}
				<span class="navbar-brand">{{feature.name}}</span>
                <span/> {% comment %} navbar is a flexbox, this span centers the feature name {% endcomment %}
				{% endif %}
			</nav>
            {% endblock %}
		</header>
		<div class="row mt-1">
			<aside class="col-2 flex-column">
				{% block sidebar %}
				{% include "feats/_sidebar.html" with features=features feature=feature only %}
				{% endblock %}
			</aside>
			<main class="col-10">
				{% block main %}
				{% endblock %}
			</main>
		</div>
		<footer class="row">
			{% block footer %}{% endblock %}
		</footer>
	</body>
</html>

feats/django/templates/feats/add_selector.html
{% extends "feats/_template.html" %}

{% block main %}
{% comment %} TODO: Move the shared feature detail into an include {% endcomment %}
<section>
    <h1> Add Selector for {{ feature.name }} </h1>
</section>
<section>
    <h2>Implementations</h2>
    <dl>
        {% for name, impl in feature.feature.implementations.items %}
        <dt>
            {% if impl is feature.feature.default_implementation %}
            (Default)
            {% endif %}
            {{ name }}
        </dt>
        <dd>
            {% if impl.description %}
                {{ impl.description }}
            {% else %}
                No description provided
            {% endif %}
        </dd>
        {% endfor %}
    </dl>
</section>
<section>
    <h2>Selector Types</h2>
    <p>
    All newly created selectors are "inactive" until they have been mapped to
    a segment.
    </p>
    <nav>
        <div class="nav nav-tabs" id="selector-types" role="tablist">
            <a class="nav-link active" id="static-tab" data-toggle="tab" href="#static" role="tab" aria-controls="static" aria-selected="true">Static</a>
            <a class="nav-link" id="rollout-tab" data-toggle="tab" href="#rollout" role="tab" aria-controls="rollout" aria-selected="false">Rollout</a>
            <a class="nav-link" id="experiment-tab" data-toggle="tab" href="#experiment" role="tab" aria-controls="experiment" aria-selected="false">Experiment</a>
        </div>
    </nav>
    <div class="tab-content" id="selector-type-forms">
        <div class="tab-pane active show" id="static" role="tabpanel" aria-labelledby="static-tab">
            <p>
            Always selects a single implementation to be used for the linked
            segments.
            </p>
            <form method="POST" action="">
                {% csrf_token %}
                {% include "feats/_render_form.html" with form=forms.static only %}
                <input type="submit" class="btn btn-primary" value="Submit"/>
            </form>
        </div>
        <div class="tab-pane" id="rollout" role="tabpanel" aria-labelledby="rollout-tab">
            <p>
                Deterministically selects an implementation based on the relative
                weights between different implementations.

                Rollouts are designed to be able to change the weights after the
                initial setup in order to expand the audience for an implementation.

                Objects will always receive the same implementation as long as the
                weights do not change.

                Useful for doing releases of new features or implementations.
            </p>
            <form method="POST" action="">
                {% csrf_token %}
                {% include "feats/_render_form.html" with form=forms.rollout only %}
                <input type="submit" class="btn btn-primary" value="Submit"/>
            </form>
        </div>
        <div class="tab-pane" id="experiment" role="tabpanel" aria-labelledby="experiment-tab">
            <p>
                Randomly selects an implementation based on the relative weights
                between different implementations.

                Stores the results of previous selections to ensure objects
                always receive the same implementation regardless of how the
                configured weights change.

                Useful for doing product A/B tests.
            </p>
            <form method="POST" action="">
                {% csrf_token %}
                {% include "feats/_render_form.html" with form=forms.experiment only %}
                <input type="submit" class="btn btn-primary" value="Submit"/>
            </form>
        </div>
    </div>
</section>
{% endblock %}

feats/django/templates/feats/change.html
{% extends "feats/_template.html" %}

{% block main %}
{% comment %} TODO: Move the shared feature detail into an include {% endcomment %}
<section>
    <h1> {{ feature.name }} </h1>
    {% if feature.feature.description %}
    <p class="lead">{{ feature.feature.description }}</p>
    {% endif %}
</section>
<section>
    <h2>Options</h2>
    <dl>
        {% for name, impl in feature.feature.implementations.items %}
        <dt>
            {% if impl is feature.feature.default_implementation %}
            (Default)
            {% endif %}
            {{ name }}
        </dt>
        <dd>
            {% if impl.description %}
                {{ impl.description }}
            {% else %}
                No description provided
            {% endif %}
        </dd>
        {% endfor %}
    </dl>
</section>
<section>
    <h2>Configuration</h2>

</section>
{% endblock %}

feats/django/templates/feats/change_selector.html
{% extends "feats/_template.html" %}
{% load selector_type from feats %}

{% block main %}
{% comment %} TODO: Move the shared feature detail into an include {% endcomment %}
<section>
    <h1> {{selector.name }} of {{ feature.name }} </h1>
</section>
<section>
    <h2>Options</h2>
    <dl>
        {% for name, impl in feature.feature.implementations.items %}
        <dt>
            {% if impl is feature.feature.default_implementation %}
            (Default)
            {% endif %}
            {{ name }}
        </dt>
        <dd>
            {% if impl.description %}
                {{ impl.description }}
            {% else %}
                No description provided
            {% endif %}
        </dd>
        {% endfor %}
    </dl>
</section>
<section>
    <h2>Configuration</h2>
    <form method="POST" action="">
	    {% csrf_token %}
	    {% include "feats/_render_form.html" with form=form %}
	    <input type="submit" class="btn btn-primary" value="Update"/>
    </form>
</section>
{% endblock %}

feats/django/templates/feats/detail.html
{% extends "feats/_template.html" %}

{% block main %}
<section>
    {% if feature.feature.description %}
    <p class="lead"/>{{ feature.feature.description }}</p>
    {% endif %}
</section>
<section>
    <h2> Implementations </h2>
    <dl>
        {% for name, impl in feature.feature.implementations.items %}
        <dt>
            {% if impl is feature.feature.default_implementation %}
            (Default)
            {% endif %}
            {{ name }}
        </dt>
        <dd>
            {% if impl.description %}
                {{ impl.description }}
            {% else %}
                No description provided
            {% endif %}
        </dd>
        {% endfor %}
    </dl>
</section>
<section>
    <h2>
        Configuration
    </h2>
    {% if feature.feature.input_types %}
	<section>
		<h3>Segmentation
		<a href="{% url 'feats:update-segmentation' feature.name %}">✎</a>
        </h3>
		{% if state.selector_mapping.items %}
        <table class="table table-hover">
            <thead>
                <tr>
                    {% for segment in segment_names %}
                    <th>
                        {{segment}}
                    </th>
                    {% endfor %}
                    <th>
                        Selector
                    </th>
                </tr>
            </thead>
            <tbody>
	{% for mapping, selector in state.selector_mapping.items %}
                <tr>
                {% for segment_value in mapping %}
                <td> {{ segment_value }} </td>
                {% empty %}
                {% for segment in segment_names %}
                <td> * </td>
                {% endfor %}
                {% endfor %}
                <td> {{ selector.name }} </td>
                </tr>
	{% endfor %}
            </tbody>
        </table>
        {% else %}
		No Segmentation Specified
		{% endif %}

	</section>
	<section>
		<h3>Selectors</h3>
		<dl>
		{% for selector in state.selectors %}
		<dt>
		{{ selector.name }} 
		<a href="{% url 'feats:update-selector' feature.name forloop.counter0 %}">✎</a>
		</dt>
		<dd>
		{% include "feats/_selector.html" with selector=selector only %}
		</dd>
		{% empty %}
		<p>No selectors configured. The default implementation will always be used.</p>
		{% endfor %}
		</dl>
		<a href="{% url 'feats:add-selector' feature.name %}">Add Selector</a>
	</section>
    {% else %}
       TODO: No-args
    {% endif %}
</section>


{% endblock %}

feats/django/templates/feats/edit_segmentation.html
{% if feature.valid_segments %}
<form>
    <select required multiple>
        <option value=""> Select at least one Segment </option>
        {% for name, segment in feature.valid_segments.items %}
        <option value="{{name}}">{{name}}</option>
        {% endfor %}
    </select>
</form>
{% else %}
<p>
There are no registered segments which match the required input type for
this feature.

A segment which can handle {{feature.input_type}} will need to be registered.
</p>
{% endif %}

feats/django/templates/feats/index.html
{% extends "feats/_template.html" %}

{%block main %}
Lorem Ipsum What Goes on The Index Page?
{%endblock%}